server:
  port: 8888
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: ${APPLICATION_IP}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000