# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8080
  contextPath: /
  session:
    timeout: 10

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://127.0.0.1:7070/authserver/oauth/token
      userAuthorizationUri: http://127.0.0.1:7070/authserver/oauth/authorize
      clientId: first
      clientSecret: passwordforauthserver
      refresh-token-validity-seconds: 60
      access-token-validity-seconds: 2592000
    resource:
      userInfoUri: http://127.0.0.1:9000/user

person:
  url: http://127.0.0.1:9000/person

# Proxies the calls to http://localhost:8080/api/* to our REST service at http://localhost:9000/*
# and automatically includes our OAuth2 token in the request headers
zuul:
  SendErrorFilter:
    post:
      desable: true
  routes:
    resource:
      path: /api/**
      url: http://127.0.0.1:9000
    system:
      path: /system/**
      url: http://127.0.0.1:9001
    user: 
      path: /user/**
      url: http://127.0.0.1:9000/user
    auth:
      path: /auth/**
      url: http://127.0.0.1:7070

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/