# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8080
  contextPath: /
  session:
    timeout: 1800


# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://${APPLICATION_IP}:7070/authserver/oauth/token
      userAuthorizationUri: http://${APPLICATION_IP}:7070/authserver/oauth/authorize
      clientId: first
      clientSecret: passwordforauthserver
      refresh-token-validity-seconds: 3600
      access-token-validity-seconds: 3000
    resource:
      userInfoUri: http://${APPLICATION_IP}:9000/user

person:
  url: http://${APPLICATION_IP}:9000/person

# zuul 代理
zuul:
  SendErrorFilter:
    post:
      desable: true
  routes:
    resource:
      path: /api/**
      url: http://${APPLICATION_IP}:9000
    system:
      path: /system/**
      url: http://${APPLICATION_IP}:9001
    user: 
      path: /user/**
      url: http://${APPLICATION_IP}:9000/user
    auth:
      path: /auth/**
      url: http://${APPLICATION_IP}:7070
    bpm:
      path: /bpm/**
      url: http://${APPLICATION_IP}:6789

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2

eureka:
  client:
    serviceUrl:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/
spring:
  application:
    name: springcloud-zuul-getway-server
  redis:
    database: 0
    host: ${APPLICATION_IP}
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0